build: false
shallow_clone: true
platform: 'x86'
clone_folder: c:\projects\cakephp-multi-column-uniquness
branches:
  except:
    - gh-pages
environment:
  global:
    PHP: "C:/PHP"
    DATABASE_URL: "sqlserver://sa:Password12!@.\SQL2012SP1/cakephp"
    DATABASE_TEST_URL: "sqlserver://sa:Password12!@.\SQL2012SP1/cakephp"
  matrix:
      - db: 2012
        db_dsn: 'sqlserver://sa:Password12!@.\SQL2012SP1/cakephp?MultipleActiveResultSets=false'
services:
  - mssql2012sp1
init:
  - SET PATH=C:\php\;%PATH%
install:
  - cd c:\
  - ps: Start-FileDownload 'http://ci.cakephp.org/php.zip'
  - 7z x php.zip -oc:\php
  - cd c:\php
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_sqlsrv.dll >> php.ini
  - echo extension=php_pdo_sqlsrv.dll >> php.ini
  - echo extension=php_pdo_mysql.dll >> php.ini
  - echo extension=php_intl.dll >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - cd c:\projects\cakephp-multi-column-uniquness
  - mkdir MultiColumnUniqueness
  - mv *.* MultiColumnUniqueness
  - php -r "readfile('https://getcomposer.org/installer');" | php
  - php composer.phar -sdev create-project friendsofcake/app-template cakephp-plugin --keep-vcs
  - mv MultiColumnUniqueness cakephp-plugin\Plugin\MultiColumnUniqueness
test_script:
  - sqlcmd -S ".\SQL2012SP1" -U sa -P Password12! -Q "create database cakephp;"
  - cd c:\projects\cakephp-multi-column-uniquness\cakephp-plugin\app
  - Console\cake.bat test MultiColumnUniqueness AllMultiColumnUniqueness --stderr
